[package]
name = "ccgame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
color-eyre = "0.5"
toml = "0.8.2"
zip_archive = "1.2.2"
