name: HTML Generation
run-name: HTML files are being generated
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4 
      - name: run script
      - run: cargo run && git add . && git commit -m "auto html build" && git push 

