name: HTML Generation
run-name: HTML file generation
on: [push]
permissions:
  contents: write
jobs:
  html-gen:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4 
      - name: run script
        run: ./release/ccgame 
      - name: commit files
        run: |
          git config --global user.name 'JamieH01'
          git config --global user.email 'JamieH01@users.noreply.github.com'
        git add . && git commit -m "auto html build" && git push || echo 'no new files to commit'

